// GENERATED by exp/v65cpp_tools/gen_params.py from exp/v65q/params.py -- do not edit by hand
#pragma once

// Phase-Shifted Economy rules
inline constexpr int SPLIT_UNTIL = 250;
inline constexpr int SPLIT_AT = 4;
inline constexpr int CHILD_SIZE = 2;
inline int MAX_UNITS = 48;
inline constexpr int KING_LENGTH = 12;
inline int MIN_SWARM_UNITS = 24;
// POPULATION RESCUE: kings/long dragons split a RESCUE_CHILD every RESCUE_EVERY rounds while units are
// below RESCUE_FRAC of the unit cap (off during cash-in unless units <= RESCUE_CASH_UNITS)
inline constexpr int RESCUE_ENABLE = 1;
inline constexpr double RESCUE_FRAC = 0.25;
inline constexpr int RESCUE_EVERY = 5;
inline constexpr int RESCUE_CHILD = 2;
inline constexpr int RESCUE_CASH_UNITS = 2;
// Maps with area over BIG_MAP_AREA use these instead (e.g. schooltime, big_empty)
inline constexpr int BIG_MAP_AREA = 2000;
inline constexpr int BIG_MAX_UNITS = 64;
inline constexpr int BIG_MIN_SWARM_UNITS = 64;

// Sonar
inline constexpr int MIN_PEARL_CLUSTER = 3;
inline constexpr double SONAR_PING_PROB = 0.5;
inline constexpr int SPAWN_SONAR_ENABLE = 0;

// Movement & Heuristic Weights
inline constexpr double PEARL_W = 84.0;
inline constexpr double MEMORY_PEARL_W = 21.0;
inline constexpr double SPAWN_W = 25.0;
inline constexpr int SPAWN_HORIZON = 60;
inline constexpr int SEARCH_NODES = 250;
inline constexpr int SPACE_MARGIN = 10;
inline constexpr int SPACE_CAP = 100;
inline constexpr int SPACE_LEN_MULT = 2;
inline constexpr double TRAP_PEN = 6.0;

inline constexpr int SCOUT_ROUNDS = 50;
inline constexpr double PORTAL_PEN = 8.0;
inline constexpr double PORTAL_STALE_PEN = 15.0;
inline constexpr int PORTAL_STALE_GRACE = 2;
inline constexpr double PORTAL_STALE_RATE = 0.8;
inline constexpr double PORTAL_SCOUT_MULT = 0.7;
inline constexpr double PORTAL_PARANOIA_RAMP = 200.0;
inline constexpr double PORTAL_UNKNOWN_PEN = 20.0;
// Portals whose far end we know: cost this instead of PORTAL_PEN (set KNOWN_PORTAL_PEN = PORTAL_PEN for old),
// and the revisit penalty on a portal's exit tile is scaled by PORTAL_EXIT_VISIT_MULT (1.0 = old)
inline constexpr double KNOWN_PORTAL_PEN = 2.0;
inline constexpr double PORTAL_EXIT_VISIT_MULT = 0.0;
// PORTAL TRAFFIC: one of our dragons per portal edge. Taken = a teammate went through this edge (from
// either tile touching it) within PORTAL_TAKEN_TTL rounds; the partner edge (exit side) is separate.
// Busy = an enemy touched the portal within PORTAL_BUSY_TTL rounds (its tail may sit past the exit).
// Claimed = a teammate head within PORTAL_CLAIM_DIST is closer to the edge than us.
// 1 = unexplored-portal penalty ramps with the dragon's own age (newborns are not afraid); 0 = game round
inline constexpr int PORTAL_AGE_RAMP = 1;
inline constexpr int PORTAL_TRAFFIC_ENABLE = 1;
inline constexpr int PORTAL_TAKEN_TTL = 60;
inline constexpr double PORTAL_TAKEN_PEN = 60.0;
inline constexpr int PORTAL_BUSY_TTL = 2;
inline constexpr double PORTAL_BUSY_PEN = 60.0;
inline constexpr int PORTAL_CLAIM_DIST = 3;
inline constexpr double PORTAL_CLAIM_PEN = 15.0;
// 1 = blind-wrap check only blocks real map-edge wraps, so search can see through known portals
inline constexpr int PORTAL_LOOKTHROUGH = 1;

inline constexpr double HEAD_RISK = 28.0;
inline constexpr double TEAM_CUT_PEN = 150.0;
inline constexpr double TEAM_NEAR_PEN = 1.5;
inline constexpr int TEAM_NEAR_RADIUS = 2;
inline constexpr int FANOUT_ROUNDS = 20;
inline constexpr double FANOUT_TEAM_MULT = 5.0;
inline constexpr int CROWD_MATES = 3;
inline constexpr double CROWD_TEAM_MULT = 3.5;

inline constexpr double LETHAL_PEN = 100.0;
inline constexpr int LETHAL_SLACK = 2;
inline constexpr double VISIT_PEN = 2.8;
inline constexpr double EXPLORE_W = 16.8;
// 1 = search seeds first moves as forward, left, right, back of each dragon's starting heading
// (children: their parent's), so both sides get the same exploration tilt. 0 = fixed N,E,S,W.
inline constexpr int SEED_ORDER_ENABLE = 1;
inline constexpr double STRAIGHT_BONUS = 0.5;
inline constexpr double NOISE_W = 0.3;
inline constexpr int OTHER_TTL = 2;
inline constexpr int VACATE_MARGIN = 1;
inline constexpr int HUNT_ENABLE = 1;
inline constexpr int HUNT_MAX_LEN = 5;
inline constexpr int HUNT_MIN_UNITS = 3;
inline constexpr int HUNT_MIN_ENEMY_SEGS = 8;
inline constexpr double HUNT_WINDOW_FRAC = 0.3;
inline constexpr double HUNT_KILL_W = 1000.0;
inline constexpr double HUNT_W = 25.0;
inline constexpr double HUNT_ADJ_W = 8.0;
inline constexpr int HUNT_ENDGAME_LEN = 3;
inline constexpr int HUNT_GUARD_DIST = 4;
inline constexpr int SPRINT_ENABLE = 1;
inline constexpr int TRAP_ENABLE = 1;
inline constexpr int TRAP_RADIUS = 4;
inline constexpr int TRAP_MAX_HEADS = 1;
inline constexpr int TRAP_CAP = 20;
inline constexpr double TRAP_KILL_W = 60.0;
inline constexpr double SQUEEZE_W = 2.0;
inline constexpr double CORRIDOR_PEN = 8.0;
inline constexpr int CORRIDOR_MIN = 2;
inline constexpr int ENDGAME_ROUND = 400;
inline constexpr double ENDGAME_SPACE_MULT = 2.0;
inline constexpr double ENDGAME_PORTAL_PEN = 40.0;

inline constexpr int THREAT_LEN_MARGIN = 8;
inline constexpr int THREAT_TTL = 3;
inline constexpr int ESCAPE_KEEP = 2;
inline constexpr int ANCHOR_ENABLE = 1;
inline constexpr int ANCHOR_BORN_BY = 1;
inline constexpr int ANCHOR_SPLITS = 64;
inline constexpr int ANCHOR_SPLIT_UNTIL = 250;
inline constexpr int ANCHOR_SPLIT_AT = 4;
inline constexpr int ANCHOR_CHILD = 2;
inline constexpr double ANCHOR_SPACE_MULT = 1.5;
inline constexpr double ANCHOR_HEAD_MULT = 2.0;
inline constexpr double ANCHOR_PORTAL_MULT = 2.0;
inline constexpr int ANCHOR_HUNT = 0;
inline constexpr int ANCHOR_EMERGENCY_SPLIT = 1;
inline constexpr int LONG_ENABLE = 1;
inline constexpr int LONG_ROUND = 80;
inline constexpr int LONG_MIN_LEN = 5;
inline constexpr double LONG_PEARL_MULT = 2.5;
inline constexpr int LONG_SAFE_ROUND = 450;
inline constexpr double LONG_SAFE_HEAD_MULT = 2.0;
inline constexpr double LONG_SAFE_SPACE_MULT = 1.5;
inline constexpr int LONG_NO_ESPLIT = 0;
inline constexpr int DEADEND_PEN = 0;
inline constexpr int DEADEND_MAX = 30;
inline constexpr int UNIT_AREA = 0;
inline constexpr int UNIT_MIN = 6;

inline constexpr int KP_ENABLE = 1;
inline constexpr int KP_ROUND = 250;
inline constexpr int KP_MIN_LEN = 6;
inline constexpr double KP_NEAR_PEN = 40.0;
inline constexpr double KP_FAR_W = 20.0;
inline constexpr double KP_PEARL_CAP = 70.0;

inline constexpr int NEAR2_ENABLE = 1;
inline constexpr double NEAR2_PEN = 3.0;
inline constexpr int CASH_ENABLE = 1;
inline int CASH_ROUND = 420;
inline constexpr int CASH_ROUND_BIG = 330;
inline constexpr int CASH_BIG_AREA = 1100;
inline constexpr int CASH_MAXLEN = 5;
inline constexpr int CASH_KING_MIN = 6;
inline constexpr int CASH_DIST = 4;
inline constexpr double CASH_W = 80.0;
inline constexpr int FF_ENABLE = 0;
inline constexpr double FF_PEN = 80.0;

inline constexpr int S_BIRTH_ENABLE = 0;

// ---- v65e early-economy experiments ----
inline constexpr int EXPIRED_ENABLE = 0;  // value tiles whose spawn countdown expired while out of sight
inline constexpr double EXPIRED_W = 40.0;
inline constexpr double EXPIRED_TAU = 30.0;
inline constexpr int HOTVISIT_ENABLE = 0;  // no revisit penalty next to hot (short-countdown) spawn tiles
inline constexpr int HOT_GAP = 60;
inline constexpr int SYM_SEARCH = 1;  // credit tiles to every shortest-path first move (removes N>E>S>W tie bias)
inline constexpr int LONG_ANCHOR_AUTO = 1;  // v65: every anchor turns 'long' (stops splitting) at LONG_ROUND regardless of length
inline constexpr int ANCHOR_CAUTION_MINLEN = 5;  // anchors get extra space/head caution only at >= this length (v65: 0)
inline constexpr int FIRST_LIGHT = 1;  // halve the search on a child's first turn (process start-up is charged to it)
inline constexpr double HR_EVEN_MULT = 1.0;  // head-risk multiplier when the adjacent enemy head is at least our length (v65: 1.0)

// ==== cpp_x (27 Sep): merge of cpp_tact + cpp_mid + cpp_small. Every flag defaults OFF (= cpp_base).
// Three copies of numbers-aware head risk exist: TACT_NUM (enemy head-risk terms only; recommended),
// MHRN_* (cpp_mid, whole head_risk before the move loop), SHRN_* (cpp_small, whole head_risk). They compound if
// combined; enable at most one. Two fountain detectors: MILL (is_fount, needs MILL_ENABLE) and FAST_* (is_fast,
// used by FARM/FOUNT). MILL and FARM overlap: on a MILL move FARM is skipped (see choose()).

// ---- cpp_tact: tactical lookahead (27 Sep). All default OFF = cpp_base behaviour ----
// TACT_DOOM: a dragon with no passable move no longer takes its facing tile blindly: it rams an adjacent enemy
// head if any, else an unknown portal, else a wall/body (dies alone), and a friendly head only as a last resort.
inline constexpr int TACT_DOOM = 1;
// TACT_THREAT: sprint-reach threat. An enemy head of visible length le can ram any tile it reaches in
// k <= min(le-1, TACT_REACH) steps this turn. Tiles at k=2 / k=3 cost head_risk * TACT_K2 / TACT_K3 for
// dragons of length >= TACT_MIN_LEN (enemy not longer than us + TACT_LEN_SLACK).
inline constexpr int TACT_THREAT = 0;
inline constexpr int TACT_REACH = 3;
inline constexpr int TACT_MIN_LEN = 5;
inline constexpr int TACT_LEN_SLACK = 0;
inline constexpr double TACT_K2 = 0.5;
inline constexpr double TACT_K3 = 0.15;
// TACT_HUNT: small dragons also ram mid-length enemies: target if visible segs >= length + TACT_HUNT_GAP and
// segs >= TACT_HUNT_MIN (base: segs > length and segs >= HUNT_MIN_ENEMY_SEGS 8)
inline constexpr int TACT_HUNT = 0;
inline constexpr int TACT_HUNT_GAP = 2;
inline constexpr int TACT_HUNT_MIN = 5;
// TACT_LA: 2-ply corner check (me -> enemy reply -> me). For each candidate tile j of a dragon of length
// >= TACT_MIN_LEN and each enemy head within reach: if some single-step enemy reply e' (not a ram) leaves me
// no escape tile k next to j (passable next turn and at distance > TACT_LA_REACH from e'), cost
// head_risk * TACT_LA_MULT (enemy not longer than us + TACT_LEN_SLACK).
inline constexpr int TACT_LA = 0;
inline constexpr int TACT_LA_REACH = 1;
inline constexpr double TACT_LA_MULT = 0.5;
// TACT_NUM: numbers-aware head-on trading. own = visible friendly heads + 1, en = visible enemy heads.
// en >= TACT_NUM_RATIO * own (outnumbered): enemy head_risk x TACT_NUM_HI (avoid even trades);
// own >= TACT_NUM_RATIO * en (we lead): x TACT_NUM_LO, and with TACT_NUM_RAM small dragons (<= HUNT_MAX_LEN)
// also hunt/sprint-ram enemies of visible length >= their own (even trades).
inline constexpr int TACT_NUM = 1;
inline constexpr double TACT_NUM_RATIO = 1.5;
inline constexpr double TACT_NUM_HI = 2.0;
inline constexpr double TACT_NUM_LO = 0.5;
inline constexpr int TACT_NUM_RAM = 0;
// TACT_DOOM2: if every passable move has room < own length (sealed, dies within a few turns) and an enemy head is
// adjacent, ram it now (guaranteed trade) instead of dying alone later.
inline constexpr int TACT_DOOM2 = 0;
// TACT_NUM_RAM needs at least this many own heads in view (incl. self) before seeking even trades
inline constexpr int TACT_NUM_RAM_OWN = 1;

// ---- cpp_mid (27 Sep): POCKET MILL -- farm pearls in small dead-end pockets and leave by reverse split ----
// Web: on Autarky opponents eat 80-350 fountain pearls/game from 1-wide dead-end pockets (enter, eat,
// split so the tail-child walks out, parent of 2 dies); we eat 8-70 because the room check forbids pockets.
inline constexpr int MILL_ENABLE = 1;       // 0 = cpp_base behaviour
inline constexpr int MILL_POCKET_MAX = 12;  // a move enters a pocket if the static region behind it has <= this many tiles
inline constexpr int MILL_MIN_P = 3;        // pocket needs at least this many pearls (fountains count) to enter / pull
inline constexpr int MILL_MIN_FINAL = 4;    // enter only if length + pocket pearls >= this (so a reverse split is possible)
inline constexpr double MILL_COST = 21;   // score cost of entering a pocket (replaces room/lethal/corridor penalties)
inline constexpr int MILL_LONG_MINP = 3;    // long/king/anchor dragons need at least this many pearls in the pocket
inline constexpr int MILL_ENEMY_R = 3;      // no mill when an enemy head is within this distance of our head
inline constexpr int MILL_ENEMY_PATH = 0;   // 1: that distance is walking steps through the known map (not manhattan)
inline constexpr int MILL_EXIT = 1;         // in a pocket with no pearls left ahead: reverse split now (keep 2)
inline constexpr int MILL_GAP = 5;          // fountain: countdown resets observed all <= this
inline constexpr int MILL_RESETS = 2;       // resets needed before a tile counts as a fountain
inline constexpr double MILL_MEM_W = 21.0;  // search value of an out-of-sight fountain tile (a pearl has respawned)
inline constexpr int MILL_UNTIL = 470;      // no mill from this round on
inline constexpr double MILL_PULL_MULT = 1.0; // search value multiplier for pearls on dead-end (peeled) tiles, small dragons
inline constexpr int MILL_PULL_MAXLEN = 6;  // ... only for dragons up to this length (not anchor/long/king)
inline constexpr double MILL_PULL_W = 40;  // pocket farmer: bonus W/(1+d) toward the nearest free dead-end tile holding a pearl/fountain
inline constexpr int MILL_PULL_D = 14;      // ... BFS depth of that pull

// ---- cpp_mid NARROW: short dragons harvest narrow structures (web QoS: 44% of uneaten pearls sit in narrow cells) ----
inline constexpr int NARROW_ENABLE = 1;
inline constexpr int NARROW_MAXLEN = 3;       // dragons up to this length (not anchor/long) ...
inline constexpr int NARROW_NEED_ADD = 3;     // ... need only length + this much room
inline constexpr double NARROW_CPEN_MULT = 0.0; // ... and pay this fraction of the corridor penalty

// ---- cpp_mid HRN (renamed MHRN_*): numbers-aware head-on risk (web: head-ons are 1:1 trades; outnumbered even trades bleed us) ----
inline constexpr int MHRN_ENABLE = 0;
inline constexpr double MHRN_RATIO = 1.5;      // visible enemy heads >= RATIO x (own heads incl. self) -> outnumbered
inline constexpr double MHRN_UP = 2.0;         // head_risk multiplier when outnumbered
inline constexpr double MHRN_DOWN = 0.5;       // head_risk multiplier when we outnumber them by RATIO

// ---- cpp_small (27 Sep): small-map fixes, all default OFF (= cpp_base) ----
// DEAD-END DISCIPLINE: a dragon whose head can only go into pockets smaller than its body ("doomed") makes no
// voluntary split (keeps its length for the reverse/escape split at the pocket end), and a move into a pocket
// it cannot escape from (length + pocket pearls < 4, so no split is possible at the end) costs DE_TRAP_PEN.
inline constexpr int DE_ENABLE = 0;
inline constexpr int DE_SPLIT_KEEP = 99;     // doomed: allow a voluntary split only if length - child >= this
inline constexpr double DE_TRAP_PEN = 150.0;
// HEAD RISK BY LENGTH: head-risk multiplier when the adjacent enemy head is not longer than us (it can ram us
// at an even or favourable trade on its next move)
inline constexpr double HR_SHORT_MULT = 1.0;
// RAM: an adjacent enemy head whose visible length >= ours + RAM_MARGIN is rammed (any length <= RAM_MAXLEN)
inline constexpr int RAM_ENABLE = 0;
inline constexpr int RAM_MARGIN = 1;
inline constexpr int RAM_MAXLEN = 99;
inline constexpr int RAM_MIN_UNITS = 2;
// PEARL RACE: a pearl/spawn a visible enemy head reaches first (or at the same time: we would arrive first and
// be rammed) is worth RACE_LOSE_MULT / RACE_TIE_MULT of its value
inline constexpr int RACE_ENABLE = 0;
inline constexpr double RACE_LOSE_MULT = 0.25;
inline constexpr double RACE_TIE_MULT = 0.5;
inline constexpr int RACE_RADIUS = 10;
// FOUNTAINS (cpp_small): a tile is 'fast' once seen in >= FAST_OBS rounds with every countdown <= FAST_GAP
inline constexpr int FAST_GAP = 5;
inline constexpr int FAST_OBS = 3;
// POCKET FARM: a dragon of length <= FARM_MAXLEN may step into a small pocket (room < need) that holds a fast tile
// and no own dragon: the room/lethal/corridor/DE penalties are cancelled and FARM_W is added
inline constexpr int FARM_ENABLE = 0;
inline constexpr int FARM_MAXLEN = 4;
inline constexpr double FARM_W = 20.0;
// FOUNTAIN PULL: search adds FOUNT_W/(1+dist) per known fast tile (summed per first move, capped at FOUNT_CAP)
inline constexpr int FOUNT_ENABLE = 0;
inline constexpr double FOUNT_W = 30.0;
inline constexpr double FOUNT_CAP = 90.0;
// NUMBERS-AWARE HEAD RISK (cpp_small HRN, renamed SHRN_*): head_risk x SHRN_OUT_MULT when visible enemy heads >= SHRN_RATIO x (own heads incl. us),
// x SHRN_LEAD_MULT when own >= SHRN_RATIO x enemy
inline constexpr int SHRN_ENABLE = 0;
inline constexpr double SHRN_RATIO = 1.5;
inline constexpr double SHRN_OUT_MULT = 2.0;
inline constexpr double SHRN_LEAD_MULT = 0.5;
// EARLY RUSH: before RUSH_UNTIL, +RUSH_W per step that shortens the BFS distance (known kelp = walls, unknown = open)
// to the map centre (the axis of symmetry between the two starts)
inline constexpr int RUSH_ENABLE = 1;
inline constexpr int RUSH_UNTIL = 30;
inline constexpr double RUSH_W = 12.0;
inline constexpr int RUSH_MOD = 1;  // only dragons with id % RUSH_MOD == 0 rush (1 = all)
inline constexpr double RUSH_IDLE_VAL = 0.0;  // > 0: rush only when the best pearl value over all moves is below this
inline constexpr int RUSH_SCOUT = 1;  // 1: stop rushing once this dragon has seen a centre tile (scout the centre, then play normally)
inline constexpr int FAST_RESET = 0;  // 1: 'fast' also needs an observed countdown reset (seen in consecutive rounds, value not decremented)
inline constexpr double RUSH_PROB = 0.5;  // < 1: each dragon rushes with this probability (drawn once at birth)

// ==== cpp_king (27 Sep): KING SAFETY vs multi-step sprint rams + BACKUP KING. Every flag defaults OFF (= X2). ====
// Web: HB kills our leading king in the last 10-20 rounds with 2-3 step sprints from BFS 3 (84% of its late king kills).
// Sprint rule (docs/movement.md, execution-order.md): step 1 is free, every further step first removes a segment and
// needs length >= 3 before paying, so an enemy of length le can put its head up to le-1 steps away (capped at
// KS_MAXREACH; nobody on the web sprints 4). Each enemy head gets exactly one turn between our move and our next one.
// KING_SPRINT: exact BFS threat map (walls, portals, bodies) of visible enemy heads; a dragon of length >= KS_MIN_LEN
// pays KS_W * (min(len, KS_LEN_CAP)/10) * round_factor for ending its move on a tile some enemy head can reach.
// round_factor: 0 before KS_ROUND, linear to 1 at KS_FULL_ROUND, then 1 + KS_LATE_MULT * (rnd-KS_LATE_ROUND)/(500-KS_LATE_ROUND).
inline constexpr int KING_SPRINT = 1;
inline constexpr int KS_ROUND = 350;
inline constexpr int KS_FULL_ROUND = 450;
inline constexpr int KS_LATE_ROUND = 470;
inline constexpr double KS_LATE_MULT = 4.0;
inline constexpr int KS_MIN_LEN = 10;
inline constexpr int KS_KING_ONLY = 0;       // 1: only the longest known dragon (visible mates + king beacons) is protected
inline constexpr double KS_W = 200.0;
inline constexpr int KS_LEN_CAP = 50;
inline constexpr int KS_MAXREACH = 3;
inline constexpr double KS_NEAR_FRAC = 0.35;  // tile one step outside an enemy's reach: this fraction of the weight
inline constexpr int KS_SAFE_LAST = 12;       // last N rounds: threatened tiles cost KS_HARD (king plays maximally safe)
inline constexpr double KS_HARD = 5000.0;
inline constexpr int KS_ENDROOM = 1;          // last N rounds: room need of a protected dragon shrinks to rounds left + 3
// KS_ESCAPE: when every single-step move of a protected dragon is in reach, sprint 2..KS_ESC_STEPS steps to a tile out
// of reach (costs steps-1 segments) if that tile has room >= length + 2
inline constexpr int KS_ESCAPE = 1;
inline constexpr int KS_ESC_ROUND = 400;
inline constexpr int KS_ESC_STEPS = 3;
// KS_GUARD: from KS_GUARD_ROUND a dragon of length <= KS_GUARD_MAXLEN rams (sprint within its reach) an enemy head that
// could reach a visible friendly dragon of length >= KS_MIN_LEN this turn (trade a small dragon for the king's life)
inline constexpr int KS_GUARD = 0;
inline constexpr int KS_GUARD_ROUND = 400;
inline constexpr int KS_GUARD_MAXLEN = 6;
// BACKUP_KING: from BK_ROUND a dragon of length >= BK_KEEP_MIN that is at least BK_KEEP_FRAC of the superior dragon it
// would feed does not cash in (no suicide, no summons) and keeps BK_SEP from the superior's head (BK_SEP_W / (1+d))
inline constexpr int BACKUP_KING = 0;
inline constexpr int BK_ROUND = 380;
inline constexpr int BK_KEEP_MIN = 6;
inline constexpr double BK_KEEP_FRAC = 0.3;
inline constexpr int BK_SEP = 5;
inline constexpr double BK_SEP_W = 30.0;
// BK_SPLIT: a protected dragon of length >= BK_SPLIT_MIN in [BK_SPLIT_R0, BK_SPLIT_R1] that knows no mate of length >=
// BK_SPLIT_FRAC * its length splits off a rear child of BK_SPLIT_FRAC * length (once)
inline constexpr int BK_SPLIT = 0;
inline constexpr int BK_SPLIT_R0 = 440;
inline constexpr int BK_SPLIT_R1 = 480;
inline constexpr int BK_SPLIT_MIN = 36;
inline constexpr double BK_SPLIT_FRAC = 0.4;
// TEST_ASSASSIN (sparring opponent only, never for submission): HB-like late king hunter. From r350 dragons of length
// <= 6 hunt enemy heads of >= 10 visible segments and sprint up to min(len-1, 3) steps to ram them.
inline constexpr int TEST_ASSASSIN = 0;
// KS_NEAR_ESC: a tile one step outside an enemy's reach costs KS_NEAR_FRAC if it has a free neighbour at least
// reach+2 from every visible enemy head (we can step out again after the enemy approaches), else KS_TRAP_FRAC
inline constexpr int KS_NEAR_ESC = 0;
inline constexpr double KS_TRAP_FRAC = 0.6;
// ==== cpp_esplit (28 Sep): EMERGENCY SPLIT of the king under a late assassination threat. Default OFF (= KREC). ====
// Idea (nIKu): if the king sees an enemy in the end game, split so that the tail survives a ram of the head.
// A split keeps the head where it is (the split is the whole action) and the child is the rear ES child segments,
// reversed: its head is our old tail and it moves later this round. So ES_CHILD_MODE 0 (child = length - ES_KEEP) is
// a "reverse": the king continues from its tail end and a short decoy stays at the threatened head.
// ES_TRIGGER: 1 = any visible enemy head with sprint reach >= ES_A_MINREACH (nIKu's literal rule);
//             2 = our current head is inside some enemy's sprint reach (KING_SPRINT threat map);
//             3 = our chosen move ends in reach AND KS_ESCAPE found no out-of-reach sprint (no safe escape).
// Only the longest known dragon (visible mates + king beacons), from ES_ROUND, length >= ES_MIN_LEN, once per
// ES_COOLDOWN rounds (a split-born child also waits ES_COOLDOWN rounds after its birth).
// ES_TAIL_CHECK: the old tail (when known from the trajectory) must be out of every visible enemy's reach and have a
// free neighbour out of reach (the child's first move).
inline constexpr int EMERG_SPLIT = 1;
inline constexpr int ES_TRIGGER = 3;
inline constexpr int ES_ROUND = 450;
inline constexpr int ES_MIN_LEN = 10;
inline constexpr int ES_COOLDOWN = 10;
inline constexpr int ES_CHILD_MODE = 0;     // 0: child = length - ES_KEEP; 1: child = ES_FRAC * length
inline constexpr int ES_KEEP = 3;  // 3 = replay marker (other reverse splits keep 2)
inline constexpr double ES_FRAC = 0.5;
inline constexpr int ES_A_MINREACH = 2;
inline constexpr int ES_TAIL_CHECK = 1;
// ES_ROOM: the child needs room(old tail) >= min(child + 2, rounds left + 3) with the parent body blocked and the child body vacating in order (the new process has no body memory and gets trapped otherwise)
inline constexpr int ES_ROOM = 0;

// ==== cpp_grow (29 Sep): MID-GAME GROWTH on slow-spawn maps. Default OFF (= Ec450 with EMERG_SPLIT=1). ====
// Web finding: head-on trades are 1:1 in count, so the smaller side dies ~1.7x faster per dragon; the opponent starts
// ~63% of them (40% as 2-3 step sprints) and our short dragons only model distance-1 threats.
// Applies to short (length <= GR_MAXLEN), non-anchor, non-protected dragons in rounds [GR_R0, GR_R1].
// GR_NUMGATE: 1 = off while we lead locally (local_numbers() > 0), so even trades stay possible when ahead.
inline constexpr int GR_ENABLE = 0;
inline constexpr int GR_R0 = 60;
inline constexpr int GR_R1 = 350;
inline constexpr int GR_MAXLEN = 4;
inline constexpr int GR_NUMGATE = 1;
// GR_THREAT: tiles an enemy head (visible length le) reaches by a k-step sprint, 2 <= k <= min(le-1, TACT_REACH),
// cost head_risk * enemy_hr_mult * GR_K2 (k=2) / GR_K3 (k=3)
inline constexpr int GR_THREAT = 0;
inline constexpr double GR_K2 = 1.0;
inline constexpr double GR_K3 = 0.4;
// GR_REP: soft repulsion from visible enemy heads: sum over enemy heads at 2 <= d <= GR_REP_R of GR_REP_W / d (x enemy_hr_mult)
inline constexpr int GR_REP = 0;
inline constexpr int GR_REP_R = 3;
inline constexpr double GR_REP_W = 6.0;
// GR_ANCHOR: round-0 dragons (anchors) turn 'long' (stop splitting, x LONG_PEARL_MULT pearl pull) at GR_ANCHOR_ROUND
// instead of LONG_ROUND, unless (GR_ANCHOR_FAST) this anchor has seen a fast tile (then the old LONG_ROUND rule).
// Web + local: from r80 our 4 Default anchors eat 15-22 pearls that never become splits; most of them die by r300.
inline constexpr int GR_ANCHOR = 1;
inline constexpr int GR_ANCHOR_ROUND = 280;
inline constexpr int GR_ANCHOR_FAST = 1;
// fast tile for GR_ANCHOR_FAST: GR_FAST_RESETS observed countdown resets to <= GR_FAST_GAP (and never a bigger reset)
inline constexpr int GR_FAST_GAP = 10;
inline constexpr int GR_FAST_RESETS = 2;
inline constexpr int GR_DBG = 0;  // 1: log first fast-tile detection per dragon to /tmp/grow_fast.log (local test only)
// cpp_aggr AG_*: proactive mid-game aggression for non-king dragons (AG_ENABLE 0 = G1 behaviour)
inline constexpr int AG_ENABLE = 1;
inline constexpr int AG_R0 = 60;           // active rounds
inline constexpr int AG_R1 = 350;
inline constexpr int AG_MAXLEN = 6;        // only dragons up to this length (never king/long/anchor)
inline constexpr double AG_RATIO = 1.5;    // ahead: own heads in view (incl. self) >= AG_RATIO * enemy heads in view
inline constexpr int AG_MIN_OWN = 2;       // ... and at least this many own heads in view (incl. self)
inline constexpr double AG_BEHIND = 1.5;   // behind: enemy heads >= AG_BEHIND * own heads
inline constexpr int AG_RAM = 1;           // when ahead: sprint/step into a reachable enemy head
inline constexpr int AG_STEPS = 3;         // max ram steps (also limited by length-1)
inline constexpr int AG_SLACK = 1;         // ram targets with visible segs >= length - AG_SLACK
inline constexpr int AG_MINSEG = 2;        // ... and >= AG_MINSEG
inline constexpr int AG_RAM_SPRINT = 1;    // 0: only single-step rams (adjacent heads)
inline constexpr double AG_PRESS_W = 3.0;  // when ahead: bonus per manhattan step closer to the nearest enemy head
inline constexpr double AG_REG_W = 0.0;    // when behind: bonus per step closer to the nearest own head (in view)
inline constexpr double AG_HR_AHEAD = 1.0; // when ahead: extra head-risk multiplier on moves next to enemy heads
inline constexpr int AG_REACH_ADD = 0;     // 1: ram reach = length (L2 two steps, L3 three steps; the web winners do this)
inline constexpr int AG_AFTER_SPLIT = 0;   // 1: a due split goes before the AG ram
inline constexpr int AG_PEARL_REACH = 0;   // 1: also rams one step further when a pearl on the path pays for it
