# Phase-Shifted Economy rules
SPLIT_UNTIL = 250 
SPLIT_AT = 4 
CHILD_SIZE = 2
MAX_UNITS = 48
KING_LENGTH = 12
MIN_SWARM_UNITS = 24

# Sonar
MIN_PEARL_CLUSTER = 3

# Movement & Heuristic Weights
PEARL_W = 84.0
MEMORY_PEARL_W = 21.0
SPAWN_W = 25.0
SPAWN_HORIZON = 60
SEARCH_NODES = 300
SPACE_MARGIN = 10
SPACE_CAP = 100
SPACE_LEN_MULT = 2
TRAP_PEN = 6.0

SCOUT_ROUNDS = 100
PORTAL_PEN = 8.0
PORTAL_STALE_PEN = 25.0
PORTAL_STALE_GRACE = 2
PORTAL_STALE_RATE = 0.8
PORTAL_SCOUT_MULT = 0.7
PORTAL_PARANOIA_RAMP = 250.0 - SCOUT_ROUNDS
PORTAL_UNKNOWN_PEN = 100.0

HEAD_RISK = 28.0
TEAM_CUT_PEN = 20.0
TEAM_NEAR_PEN = 1.5
TEAM_NEAR_RADIUS = 2
FANOUT_ROUNDS = 20
FANOUT_TEAM_MULT = 5.0
CROWD_MATES = 3
CROWD_TEAM_MULT = 3.5

LETHAL_PEN = 100.0
LETHAL_SLACK = 2
VISIT_PEN = 2.8
EXPLORE_W = 8.4
STRAIGHT_BONUS = 0.5
NOISE_W = 0.3
OTHER_TTL = 2
VACATE_MARGIN = 1
HUNT_ENABLE = 1
HUNT_MAX_LEN = 5
HUNT_MIN_UNITS = 3
HUNT_MIN_ENEMY_SEGS = 8
HUNT_WINDOW_FRAC = 0.3
HUNT_KILL_W = 1000.0
HUNT_W = 25.0
HUNT_ADJ_W = 8.0
HUNT_ENDGAME_LEN = 3
HUNT_GUARD_DIST = 4
CORRIDOR_PEN = 8.0
CORRIDOR_MIN = 2
ENDGAME_ROUND = 400
ENDGAME_SPACE_MULT = 2.0
ENDGAME_PORTAL_PEN = 40.0

SONAR_PING_PROB = 0.2
THREAT_LEN_MARGIN = 8
THREAT_TTL = 3
ESCAPE_KEEP = 2
ANCHOR_ENABLE = 1
ANCHOR_BORN_BY = 1
ANCHOR_SPLITS = 64
ANCHOR_SPLIT_UNTIL = 250
ANCHOR_SPLIT_AT = 4
ANCHOR_CHILD = 2
ANCHOR_SPACE_MULT = 1.5
ANCHOR_HEAD_MULT = 2.0
ANCHOR_PORTAL_MULT = 2.0
ANCHOR_HUNT = 0
ANCHOR_EMERGENCY_SPLIT = 1
LONG_ENABLE = 1
LONG_ROUND = 80
LONG_MIN_LEN = 5
LONG_PEARL_MULT = 2.5
LONG_SAFE_ROUND = 450
LONG_SAFE_HEAD_MULT = 2.0
LONG_SAFE_SPACE_MULT = 1.5
LONG_NO_ESPLIT = 0
DEADEND_PEN = 0
DEADEND_MAX = 30
UNIT_AREA = 0
UNIT_MIN = 6

KP_ENABLE = 1
KP_ROUND = 250
KP_MIN_LEN = 6
KP_NEAR_PEN = 40.0
KP_FAR_W = 20.0
KP_PEARL_CAP = 70.0

NEAR2_ENABLE = 1
NEAR2_PEN = 3.0
CASH_ENABLE = 1
CASH_ROUND = 420
CASH_MAXLEN = 5
CASH_KING_MIN = 6
CASH_DIST = 4
CASH_W = 80.0
FF_ENABLE = 0
FF_PEN = 80.0

