# generated by tools/gen_mapprior.py -- do not edit
INDEX = {(54, 18): ['mp_autarky'], (64, 64): ['mp_big_empty'], (32, 32): ['mp_default'], (16, 16): ['mp_default_small'], (32, 16): ['mp_devil', 'mp_dilemma'], (25, 35): ['mp_queen_of_spades'], (60, 40): ['mp_schooltime'], (48, 24): ['mp_stronghold', 'mp_trauma'], (25, 25): ['mp_trophy']}
